# Generated by Django 4.1.7 on 2023-05-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
