# Generated by Django 4.1.7 on 2023-05-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='background_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='account',
            name='user_bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user_profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
