# Generated by Django 4.1.7 on 2023-06-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='now_member',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.URLField(),
        ),
    ]
