# Generated by Django 4.1.7 on 2023-06-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party_list', '0002_party_now_member_alter_party_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='image',
        ),
        migrations.AlterField(
            model_name='party',
            name='member_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='party_list.party')),
            ],
        ),
    ]
