# Generated by Django 4.1.7 on 2023-06-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_list', '0004_party_image_alter_party_date_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='party',
            name='date',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='party',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
