# Generated by Django 4.1.7 on 2023-06-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_list', '0005_image_alter_party_date_alter_party_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.URLField(),
        ),
    ]
